server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MicroservisauthDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#JWT
myjwt:
  secretkey: "jnflkdnfqşkjdkcşvn"
  audience: "audience"
  issuer: "issuer"